import{S as v,i as S,a as w}from"./assets/vendor-e6ae6a6a.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const b="41875605-6b47be3c8e074a549a6d5f149",E="https://pixabay.com/api";async function d(t,a=1){return w.get(`${E}/`,{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:3,page:a}}).then(({data:n})=>n.hits)}const o={searchForm:document.querySelector("form"),imagesContainer:document.querySelector(".gallery-container"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")};let l="",c=1;const u={noImages:"Sorry, there are no images matching your search query. Please try again!",enterQuery:"Please enter a search query!"};o.searchForm.addEventListener("submit",q);async function q(t){t.preventDefault(),o.imagesContainer.innerHTML="",c=1;const a=t.currentTarget;if(l=a.elements.input.value.trim(),!l){o.imagesContainer.innerHTML="",h(u.enterQuery);return}try{p();const n=await d(l);f(n),n.length>0?(o.loadMoreBtn.classList.remove("is-hidden"),o.loadMoreBtn.addEventListener("click",m)):o.loadMoreBtn.classList.add("is-hidden")}catch{I()}finally{y(),a.reset()}}async function m(){c+=1,o.loadMoreBtn.classList.add("is-hidden"),p();try{const t=await d(l,c);f(t),o.loadMoreBtn.classList.remove("is-hidden")}catch(t){console.log(t)}finally{y(),c===data.totalHits&&(o.loadMoreBtn.classList.add("is-hidden"),o.loadMoreBtn.removeEventListener("click",m))}}function f(t){const a=({webformatURL:i,largeImageURL:e,tags:r,likes:s,views:g,comments:L,downloads:M})=>`
      <li class="gallery">
      <a href="${e}">
        <img class="image-preview" src="${i}" alt="${r}">
      </a>
      <div class="image-description">
      <p>Likes ${s}</p>
      <p>Views ${g}</p>
      <p>Comments ${L}</p>
      <p>Downloads ${M}</p>
      </div>
    </li>
    `,n=t.map(a).join("");o.imagesContainer.insertAdjacentHTML("beforeend",n),B.refresh()}const B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function I(){h(u.noImages)}function h(t,a="white",n="topRight",i="red"){S.show({message:t,messageColor:a,position:n,color:i})}function p(){o.loader.classList.remove("is-hidden")}function y(){o.loader.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
