import{S,i as b,a as B}from"./assets/vendor-e6ae6a6a.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const q="41875605-6b47be3c8e074a549a6d5f149",E="https://pixabay.com/api";let d="",u=1,f=0,m=40;async function g(o,a=1){const r=await B.get(`${E}/`,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m,page:a}}),{hits:n,totalHits:e}=r.data;return f=Math.ceil(e/m),{hits:n,totalHits:e}}const t={searchForm:document.querySelector("form"),imagesContainer:document.querySelector(".gallery-container"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")};t.searchForm.addEventListener("submit",R);const I=t.imagesContainer.getBoundingClientRect().height;async function R(o){o.preventDefault(),t.imagesContainer.innerHTML="",u=1;const a=o.currentTarget;if(d=a.elements.input.value.trim(),!d){t.imagesContainer.innerHTML="",c(l.enterQuery),h(),t.loadMoreBtn.classList.add("is-hidden");return}try{const{hits:r,totalHits:n}=await g(d);y(r),r.length>0&&r.length!==n?(L(),t.loadMoreBtn.classList.remove("is-hidden"),t.loadMoreBtn.addEventListener("click",p),window.scrollBy({top:I,behavior:"smooth"})):(t.loadMoreBtn.classList.add("is-hidden"),r.length===0?c(l.noImages):c(l.endOfResults))}catch{c(l.noImages)}finally{h(),a.reset()}}async function p(){u+=1,t.loadMoreBtn.classList.add("is-hidden"),L();try{const{hits:o}=await g(d,u);y(o),u<f?t.loadMoreBtn.classList.remove("is-hidden"):(t.loadMoreBtn.classList.add("is-hidden"),c(l.endOfResults),t.loadMoreBtn.removeEventListener("click",p))}catch(o){console.log(o)}finally{h()}}function y(o){const a=({webformatURL:n,largeImageURL:e,tags:s,likes:i,views:M,comments:v,downloads:w})=>`
      <li class="gallery">
      <a href="${e}">
        <img class="image-preview" src="${n}" alt="${s}">
      </a>
      <div class="image-description">
      <p>Likes ${i}</p>
      <p>Views ${M}</p>
      <p>Comments ${v}</p>
      <p>Downloads ${w}</p>
      </div>
    </li>
    `,r=o.map(a).join("");t.imagesContainer.insertAdjacentHTML("beforeend",r),O.refresh()}const O=new S(".gallery a",{captionsData:"alt",captionDelay:250}),l={noImages:"Sorry, there are no images matching your search query. Please try again!",enterQuery:"Please enter a search query!",endOfResults:"We're sorry, but you've reached the end of search results."};function c(o,a="white",r="topRight",n="red"){b.show({message:o,messageColor:a,position:r,color:n})}function L(){t.loader.classList.remove("is-hidden")}function h(){t.loader.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
