import{S as w,i as S,a as b}from"./assets/vendor-e6ae6a6a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="41875605-6b47be3c8e074a549a6d5f149",B="https://pixabay.com/api";let l="",c=1,d=0;async function u(t,r=1){const s=await b.get(`${B}/`,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:r}}),{hits:n,totalHits:e}=s.data;return d=Math.ceil(e/r),{hits:n}}const a={searchForm:document.querySelector("form"),imagesContainer:document.querySelector(".gallery-container"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")},f={noImages:"Sorry, there are no images matching your search query. Please try again!",enterQuery:"Please enter a search query!",endOfResults:"We're sorry, but you've reached the end of search results."};a.searchForm.addEventListener("submit",E);async function E(t){t.preventDefault(),a.imagesContainer.innerHTML="",c=1;const r=t.currentTarget;if(l=r.elements.input.value.trim(),!l){a.imagesContainer.innerHTML="",y(f.enterQuery);return}try{p();const s=await u(l);h(s.hits),s.hits.length>0?(a.loadMoreBtn.classList.remove("is-hidden"),a.loadMoreBtn.addEventListener("click",m)):a.loadMoreBtn.classList.add("is-hidden")}catch(s){console.log(s)}finally{g(),r.reset()}}async function m(){c+=1,a.loadMoreBtn.classList.add("is-hidden"),p();try{const{hits:t}=await u(l,c);h(t),a.loadMoreBtn.classList.remove("is-hidden")}catch(t){console.log(t)}finally{g()}c===d&&(a.loadMoreBtn.classList.add("is-hidden"),a.loadMoreBtn.removeEventListener("click",m),y(f.endOfResults))}function h(t){const r=({webformatURL:n,largeImageURL:e,tags:o,likes:i,views:L,comments:M,downloads:v})=>`
      <li class="gallery">
      <a href="${e}">
        <img class="image-preview" src="${n}" alt="${o}">
      </a>
      <div class="image-description">
      <p>Likes ${i}</p>
      <p>Views ${L}</p>
      <p>Comments ${M}</p>
      <p>Downloads ${v}</p>
      </div>
    </li>
    `,s=t.map(r).join("");a.imagesContainer.insertAdjacentHTML("beforeend",s),$.refresh()}const $=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(t,r="white",s="topRight",n="red"){S.show({message:t,messageColor:r,position:s,color:n})}function p(){a.loader.classList.remove("is-hidden")}function g(){a.loader.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
